# Generated by Django 5.2.4 on 2025-07-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0002_categorymodel_productmodel_cartmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="added_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
