# Generated by Django 5.2.4 on 2025-07-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0003_alter_cartmodel_added_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
