# Generated by Django 5.2.4 on 2025-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0004_rename_name_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.CharField(blank=True, null=True),
        ),
    ]
