# Generated by Django 5.2.4 on 2025-07-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0005_alter_productmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
